### ISSUE TITLE
[Bug] The scrollbar issue after workbook unit disposed and recreated

### ISSUE THREAD

**Issue by MurphyHou123** [dream-num/univer#3183] opened 2024-08-26 06:40 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

Univer 0.29

### Reproduction link

https://sheetsvitedemo-s2r2--5173--9569b1ab.local-corp.webcontainer.io/
it's very simple to reproduce. Use univerAPI.disposeUnit(workbook.getUnitId()) and then rebuild the workbook by workbook = univer.createUnit<IWorkbookData, Workbook>(UniverInstanceType.UNIVER_SHEET, {}).

### Expected behavior

After rebuild the workbook, the vertical scroll bar can show accurate.

### Actual behavior

After rebuild the workbook, the vertical scroll bar can only show about 42 rows. the row number more than 42 can't be shown.

**Comment by jikkai** [comment] 2024-08-26 06:48
Invalid link.

**Comment by jikkai** [comment] 2024-08-26 08:00
Duplicate of #2836

**Closed by jikkai** 2024-08-26 08:00 UTC
Labels: need reproduction
