### ISSUE TITLE
[Bug] The script plug-in cannot focus the cursor and the console reports an error

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#3728] opened 2024-10-12 09:11 UTC
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

![aaaa](https://github.com/user-attachments/assets/ec4b8445-82fc-4c63-90ce-fb0c66fae258)

### 预期行为

能输入脚本内容

### 实际行为

无法输入脚本内容

### 运行环境

Chrome

**Comment by jikkai** [comment] 2024-10-12 09:18
Please confirm whether you have correctly configured the monaco-editor worker. If it is indeed configured correctly, please provide the minimal reproduction.

![image](https://github.com/user-attachments/assets/b35492c3-b3d4-4bab-8b1f-c7e7a33f1662)

**Comment by jikkai** [comment] 2024-10-21 07:46
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-10-21 07:46 UTC
Labels: need reproduction
