### ISSUE TITLE
How to extend context menu

### ISSUE THREAD

**Issue by JackieCheung** [dream-num/univer#2061] opened 2024-04-24 07:56 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.7

### Reproduction link

I want to add a custom menu item in the right-click menu, is there any way to extend it?

### Expected behavior

want to add custom menu items

### Actual behavior

unable to find a method to extend the context menu

**Comment by jikkai** [comment] 2024-04-24 09:31
Duplicate of #1343

**Closed by jikkai** 2024-04-24 09:31 UTC
Labels: bug
