### ISSUE TITLE
[Bug] Underline cannot be displayed when the font-family is SimSun and the font-size is 12

### ISSUE THREAD

**Issue by VanessaWang1110** [dream-num/univer#4027] opened 2024-11-11 03:10 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.1

### Reproduction link

![image](https://github.com/user-attachments/assets/d16c04cc-b034-49c5-801d-639e0b1677a1)

### Expected behavior

Underline can be displayed

### Actual behavior

Underline cannot be displayed

**Comment by jikkai** [comment] 2024-11-13 05:32
@Jocs I suspect that this issue might require some additional information to reproduce, as the text size in the screenshot doesn't seem to be 12pt 🤨. However, I think you can first take a look at this issue.

**Comment by Jocs** [comment] 2024-11-17 15:57
@lumixraku I think it maybe a render issue, pls take a look.

**Comment by lumixraku** [comment] 2024-11-28 06:14
@VanessaWang1110  
 I have not been able to reproduce this issue on my Windows system; it works fine at DPI settings of 100%, 125%, 150%, and 175%. If you can provide some information related to DPI and scaling, it may help in diagnosing this issue.

**Comment by jikkai** [comment] 2024-12-03 06:17
Since you have not provided a reproduction according to the community guidelines, we will close this issue. Once you have prepared a reproduction, feel free to reopen it at any time.

**Closed by jikkai** 2024-12-03 06:17 UTC
Labels: need more info, scope:layout, need reproduction
