### ISSUE TITLE
I want to modify the top of the sheet without changing the source code, such as the position of the summation formula icon, or modify the content in the right-click menu. Is there such a plug-in? I think Univer/UI can do it, but I don’t quite understand it.

### ISSUE THREAD

**Issue by young-tree** [dream-num/univer#2217] opened 2024-05-11 01:09 UTC
### Discussed in https://github.com/dream-num/univer/discussions/2216

<div type='discussions-op-text'>

<sup>Originally posted by **young-tree** May 11, 2024</sup>
![image](https://github.com/dream-num/univer/assets/61812122/28c58a10-6971-4ced-b2bf-e4701b026a85)
</div>

**Comment by jikkai** [comment] 2024-05-11 02:40
Duplicate of #1343

**Closed by jikkai** 2024-05-11 02:40 UTC
