### ISSUE TITLE
[Feature] CSC Formula

### ISSUE THREAD

**Issue by abdelrahman830a** [dream-num/univer#2467] opened 2024-06-07 18:24 UTC
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

`CSC` Formula not implemented

### Solution

@abdelrahmanzaitoun830a: Ican solve it

Ref: https://support.google.com/docs/answer/9084103

**Comment by Dushusir** [comment] 2024-06-11 03:03
duplicate of https://github.com/dream-num/univer/issues/2425

**Closed by Dushusir** 2024-06-11 03:03 UTC
Labels: feature request
