### ISSUE TITLE
[Bug] Multiple box selection operations will cause the table to freeze

### ISSUE THREAD

**Issue by islvfz** [dream-num/univer#2368] opened 2024-05-31 06:13 UTC
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.1.11

### 复现链接

https://github.com/dream-num/univer/assets/49138080/917227d8-6def-4c67-a8ce-b14af5d0c15e

### 预期行为

希望表格操作的响应速度和一开始一样

### 实际行为

随着不停框选和滚动，表格变得越来越卡

### 运行环境

Electron

**Comment by jikkai** [comment] 2024-05-31 07:04
I'm unable to reproduce the issue you've described. Please try the latest version and provide a link that demonstrates the problem you're facing.

For now, I'm going to close this issue. However, feel free to reopen it at any time once you can provide more information that allows us to replicate the issue.

**Closed by jikkai** 2024-05-31 07:04 UTC
Labels: bug, need more info
