### ISSUE TITLE
[Bug] cell editor overflows

### ISSUE THREAD

**Issue by jerry-f** [dream-num/univer#3891] opened 2024-10-30 05:18 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

所有版本，包括最新的0.4.1

### Reproduction link

这个问题应该没有修复， 最新版本在v0.4.1 中我看到虽然将编辑器限制在工作区内了，但是实际的编辑区还是跟之前一样， 导致了可编辑区域都看不完整。见图
![image](https://github.com/user-attachments/assets/369a60f7-4f5a-4a15-90d6-aa019c84aa0d)

### Expected behavior

可编辑区域应该完整的控制在编辑区域内，且能够完整的查看到可编辑区域

### Actual behavior

现在可编辑区域在sheet 表格区域外了，并且可编辑区域有部分被隐藏了，在内容较多的时候能够体现到，见图

![image](https://github.com/user-attachments/assets/231ee133-4fa7-4ea8-8720-cb76e118b940)

### System information

Running environment
Chrome

System information
System:
OS: Windows 11 10.0.22631
Binaries:
Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
pnpm: 9.8.0 - C:\Program Files\nodejs\pnpm.CMD
Browsers:
Edge: Chromium (128.0.2739.42)
Internet Explorer: 11.0.22621.3527

**Comment by jikkai** [comment] 2024-10-30 07:07
Please provide the minimal reproduction.

**Comment by jikkai** [comment] 2024-11-09 08:44
Since we haven't received any new replies for over a week, we're temporarily closing this issue.  If you can provide more helpful information, please feel free to reopen it at any time.

**Closed by jikkai** 2024-11-09 08:44 UTC
Labels: need reproduction
