### ISSUE TITLE
[Bug] Use addFloatDomToPosition to add floating dom, and add the policy to the first sheet to follow the table scrolling. But switching to the floating dom added by the second sheet cannot follow the table scrolling.

### ISSUE THREAD

**Issue by hyman928** [dream-num/univer#3927] opened 2024-11-01 10:03 UTC
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

    const univerAPI = univerSheetRef.value?.getUniverAPI();
    const activeWorkbook = univerAPI?.getActiveWorkbook();
    const activeSheet = activeWorkbook?.getActiveSheet();

  activeSheet.addFloatDomToPosition({
        componentKey: ChartRenderWrapper,
        initPosition: {
          startX: left
          endX: left + width,
          startY: top,
          endY: top + height,
        },
        data: {},
        isVue3: true,
        allowTransform: true,
      })

### 预期行为

无论是哪个sheet表，添加浮动dom都能跟随表格滚动

### 实际行为

第一个sheet表添加的浮动dom能滚动。在第二个sheet表添加的就无法滚动，整个悬浮了

### 运行环境

Chrome

### 系统信息

  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 72.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 9.1.4 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 17.5

**Comment by jikkai** [comment] 2024-11-01 10:56
The provided information isn't enough to understand the issue. Please provide a minimal reproduction.

**Comment by hyman928** [comment] 2024-11-02 14:02
>

**Comment by hyman928** [comment] 2024-11-02 15:27
复现地址：
https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=package.json

**Comment by jikkai** [comment] 2024-11-09 08:45
Since we haven't received any new replies for over a week, we're temporarily closing this issue.  If you can provide more helpful information, please feel free to reopen it at any time.

**Closed by jikkai** 2024-11-09 08:45 UTC
Labels: need reproduction
