### ISSUE TITLE
[Bug] There is no endEditing() method on the workbook object to end the edit unit.

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#4240] opened 2024-12-06 02:05 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.2

### Reproduction link

The workbook object has a endEditing() method for ending edit units.
![aaa](https://github.com/user-attachments/assets/2f15e03a-43b1-456b-9b42-c034a17b1fa3)
![Snipaste_2024-12-06_10-00-15](https://github.com/user-attachments/assets/770cc310-1546-4d83-9048-b1f99909e3bc)

### Expected behavior

There is no endEditing() method on the workbook object to end the edit unit.

### Actual behavior

The workbook object has a endEditing() method for ending edit units.

**Comment by jikkai** [comment] 2024-12-06 02:26
Since you have not provided a reproduction according to the community guidelines, we will close this issue. Once you have prepared a reproduction, feel free to reopen it at any time.

**Closed by jikkai** 2024-12-06 02:26 UTC
Labels: bug
