### ISSUE TITLE
[Bug] After upgrading to 0.5.1, international resources cannot be found

### ISSUE THREAD

**Issue by semmywong** [dream-num/univer#4205] opened 2024-12-02 09:03 UTC
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.5.1

### 复现链接

不需要链接

### 预期行为

可以找到国际化资源

### 实际行为

找不到国际化资源

![image](https://github.com/user-attachments/assets/b6f83b45-e1d5-4e76-8a9d-261db304baee)

**Comment by jikkai** [comment] 2024-12-02 11:16
In this case, you must provide a reproduction.

**Comment by jikkai** [comment] 2024-12-03 06:16
Since you have not provided a reproduction according to the community guidelines, we will close this issue. Once you have prepared a reproduction, feel free to reopen it at any time.

**Closed by jikkai** 2024-12-03 06:16 UTC
Labels: need reproduction
