### ISSUE TITLE
[Bug] 你好，粘贴报错这个Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'ts') index.js:4292  Uncaught (in promise) Error: The color 'rgb(0 0 0/var(--tw-bg-opacity,1))' is illegal rgb color 使用的包都是0.5.1的

### ISSUE THREAD

**Issue by gulugulu-cy** [dream-num/univer#4313] opened 2024-12-15 05:04 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

    "@univerjs/core": "^0.5.1",     "@univerjs/design": "^0.5.1",     "@univerjs/docs": "^0.5.1",     "@univerjs/docs-drawing": "^0.5.1",     "@univerjs/docs-ui": "^0.5.1",     "@univerjs/drawing": "^0.5.1",     "@univerjs/drawing-ui": "^0.5.1",     "@univerjs/engine-formula": "^0.5.1",     "@univerjs/engine-render": "^0.5.1",     "@univerjs/find-replace": "^0.5.1",     "@univerjs/icons": "^0.2.8",     "@univerjs/presets": "^0.5.1",     "@univerjs/sheets": "^0.5.1",     "@univerjs/sheets-drawing": "^0.5.1",     "@univerjs/sheets-drawing-ui": "^0.5.1",     "@univerjs/sheets-filter": "^0.5.1",     "@univerjs/sheets-filter-ui": "^0.5.1",     "@univerjs/sheets-find-replace": "^0.5.1",     "@univerjs/sheets-formula": "^0.5.1",     "@univerjs/sheets-numfmt": "^0.5.1",     "@univerjs/sheets-sort": "^0.5.1",     "@univerjs/sheets-sort-ui": "^0.5.1",     "@univerjs/sheets-ui": "^0.5.1",     "@univerjs/ui": "^0.5.1",

### Reproduction link

![image](https://github.com/user-attachments/assets/136e5be5-1eea-4e6d-9307-ec3fdb52e892)
![image](https://github.com/user-attachments/assets/163ccadc-4377-4a18-863f-4290bc8344ef)

### Expected behavior

正常粘贴

### Actual behavior

粘贴错误

**Comment by jikkai** [comment] 2024-12-15 21:28
Since you have not provided a reproduction according to the community guidelines, we will close this issue. Once you have prepared a reproduction, feel free to reopen it at any time.

**Closed by jikkai** 2024-12-15 21:28 UTC
Labels: need reproduction
