### ISSUE TITLE
 [Bug] formula =I4/$I$23 =SUMIF($C:$C,V3,$I:$I) don't work! 

### ISSUE THREAD

**Issue by Picktarget** [dream-num/univer#2781] opened 2024-07-16 08:50 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.3

### Reproduction link

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts

### Expected behavior

the formula works good

### Actual behavior

the formula doesn't work

**Comment by jikkai** [comment] 2024-07-16 10:05
Duplicate of #2778

Please do not abuse issues.

**Closed by jikkai** 2024-07-16 10:05 UTC
Labels: need more info, invalid, need reproduction

**Comment by Picktarget** [comment] 2024-07-16 14:47
the link u can't see it?
