### ISSUE TITLE
[Bug] Does not save number formatting

### ISSUE THREAD

**Issue by pablo-hp** [dream-num/univer#3609] opened 2024-09-27 17:40 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

1.1.5

### Reproduction link

Add values
Create formulas
Format the numbers
And it doesn't save the formatting.

The problem occurs with a normal excel spreadsheet that has been imported.

### Expected behavior

When closing the spreadsheet, you should save the number formatting information.

### Actual behavior

When closing the spreadsheet and opening it again, the formatting of the numbers is lost.
The interesting thing is that any other modifications are saved normally, such as the sheet name, size, colors, etc.

### System information

Windows 11 23H2
Obsidian v1.6.7
Univer 1.1.5

**Comment by jikkai** [comment] 2024-09-28 02:51
We are unable to fully understand the specific problem you are encountering based on the information provided. Please provide additional details, including the plugins you have registered and whether you are utilizing Univer's backend services. A reproducible demo would be greatly appreciated.

**Comment by jikkai** [comment] 2024-10-21 07:48
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-10-21 07:48 UTC
Labels: bug, need more info, scope:numfmt
