### ISSUE TITLE
[Bug] How to disable the context menu

### ISSUE THREAD

**Issue by JackieCheung** [dream-num/univer#2253] opened 2024-05-16 07:55 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.10

### Reproduction link

the document does not provide a way to disable the context menu

### Expected behavior

disable the context menu

### Actual behavior

cannot disable the context menu

### System information

    System:
      OS: macOS 14.4.1
      CPU: (10) arm64 Apple M1 Pro
      Memory: 44.98 MB / 16.00 GB
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.0 - /usr/local/bin/node
      npm: 10.2.4 - /usr/local/bin/npm
      pnpm: 9.1.1 - ~/Library/pnpm/pnpm
    Browsers:
      Chrome: 124.0.6367.208
      Safari: 17.4.1

**Comment by jikkai** [comment] 2024-05-16 08:09
Duplicate of https://github.com/dream-num/univer/issues/1343
Duplicate of https://github.com/dream-num/univer/issues/2061

**Closed by jikkai** 2024-05-16 08:09 UTC
Labels: bug
