### ISSUE TITLE
[Bug] When scrolling, the main extension canvas style is disordered

### ISSUE THREAD

**Issue by huazhuwang** [dream-num/univer#2476] opened 2024-06-11 08:37 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.14

### Reproduction link

1. merge some cells
2. apply main extension canvas, I drew some slashes and rect, try to hide the value
3. scroll page
4. the extension canvas is disordered, and the value is shown again.

Please see the video

https://github.com/dream-num/univer/assets/51111411/5e3a779d-8af6-4929-9743-9c9c54457725

### Expected behavior

the extension canvas looks fine, and cover the value

### Actual behavior

the extension canvas is disordered, and the value is shown again

**Comment by lumixraku** [comment] 2024-07-23 06:40
Please provide a valid reproduction link.

**Comment by jikkai** [comment] 2024-09-26 09:20
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-09-26 09:20 UTC
Labels: bug, scope:rendering, Priority:P3
