### ISSUE TITLE
[Bug] `@wendellhu/redi` not export `useObservable`

### ISSUE THREAD

**Issue by semmywong** [dream-num/univer#2349] opened 2024-05-29 11:58 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.12

### Reproduction link

https://univer.ai/playground

### Expected behavior

bootstrap would't display error info.

### Actual behavior

bootstrap will display error info. e.g.
![image](https://github.com/dream-num/univer/assets/67748948/6a95e85d-b7a2-4168-bb7a-f01511b99a53)

maybe the error code.
![image](https://github.com/dream-num/univer/assets/67748948/97fcf610-8a41-40aa-b495-0520e820b720)

**Comment by jikkai** [comment] 2024-05-29 12:24
It seems that the issue was caused by an outdated demo in one of our playgrounds. We have now fixed the problem. Thank you for bringing this to our attention and for your report.

**Closed by jikkai** 2024-05-29 12:24 UTC
Labels: bug, documentation
