### ISSUE TITLE
[Bug] set cell ht = center, Causes other cells to be left aligned

### ISSUE THREAD

**Issue by Renkiee** [dream-num/univer#4160] opened 2024-11-27 02:53 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.5.0

### Reproduction link

Centering one cell causes other cells to be left aligned

### Expected behavior

Centering one cell causes other cells to be left aligned

### Actual behavior

Centering one cell causes other cells to be left aligned

**Comment by jikkai** [comment] 2024-12-03 06:16
Since you have not provided a reproduction according to the community guidelines, we will close this issue. Once you have prepared a reproduction, feel free to reopen it at any time.

**Closed by jikkai** 2024-12-03 06:16 UTC
Labels: need reproduction
