### ISSUE TITLE
[Bug] DOC adding image error and I can not get pictuer data 

### ISSUE THREAD

**Issue by DKSwang** [dream-num/univer#3500] opened 2024-09-20 08:09 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.14

### Reproduction link

Adding images smoothly without errors and able to capture data

### Expected behavior

Adding images smoothly without errors and able to capture data

### Actual behavior

Adding images smoothly without errors and able to capture data

**Comment by jikkai** [comment] 2024-09-20 08:43
Please provide the minimal reproduction.

**Comment by jikkai** [comment] 2024-09-28 03:49
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-09-28 03:49 UTC
Labels: need reproduction
