### ISSUE TITLE
[Feature] Text Formula FINDB

### ISSUE THREAD

**Issue by sagarwal3005** [dream-num/univer#2538] opened 2024-06-17 08:32 UTC
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Formula FINDB is not implemented

### Solution

Implement formula FINDB
Reference https://support.microsoft.com/en-us/office/find-findb-functions-c7912941-af2a-4bdf-a553-d0d89b0a0628
@sagarwal3005 : I can solve it

**Comment by Dushusir** [comment] 2024-10-21 07:55
Duplicate of https://github.com/dream-num/univer/issues/1812

**Closed by Dushusir** 2024-10-21 07:55 UTC
Labels: feature request, scope:formula
