### ISSUE TITLE
[Bug] Using the setValue method in Frange to set only the custom field will result in an error

### ISSUE THREAD

**Issue by lindanni** [dream-num/univer#3328] opened 2024-09-05 06:41 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.11

### Reproduction link

<img width="555" alt="1725518366(1)" src="https://github.com/user-attachments/assets/7548f954-36bc-484d-beff-a646df8a4576">
<img width="419" alt="1725518425(1)" src="https://github.com/user-attachments/assets/bbb975be-d909-4474-ae7d-f54e5429cfec">

### Expected behavior

It is expected that only the custom field can be successfully modified

### Actual behavior

Actually setting only the custom field results in an error

**Comment by jikkai** [comment] 2024-09-13 09:57
Unable to reproduce this issue in the latest version, please provide the minimum reproduction.

**Comment by jikkai** [comment] 2024-09-18 01:58
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-09-18 01:58 UTC
Labels: need reproduction
