### ISSUE TITLE
[Bug] After selecting all, use CTRL+C, and then CTRL+V in another work page, it always gets stuck, and the paste operation cannot be processed.

### ISSUE THREAD

**Issue by caijiamin** [dream-num/univer#3771] opened 2024-10-16 09:09 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

^0.2.11

### Reproduction link

在工作表1全选并按CTRL+C，在工作表2进行CTRL+V粘贴

### Expected behavior

全选后，用CTRL+C在另外一个工作页里CTRL+V直接粘贴，不会卡死

### Actual behavior

全选后，用CTRL+C在另外一个工作页里CTRL+V直接粘贴，卡死，并且不能操作表格的内容了。
（如果全选后，点右键的复制和粘贴是OK的））

**Comment by jikkai** [comment] 2024-10-16 09:21
Please confirm whether you are using the latest version and provide the minimum reproduction.

**Comment by jikkai** [comment] 2024-10-22 07:34
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-10-22 07:34 UTC
Labels: need reproduction
