### ISSUE TITLE
[Feature] Configure or pass parameters to control whether the merge confirm dialog is displayed

### ISSUE THREAD

**Issue by hurricane1998** [dream-num/univer#3778] opened 2024-10-17 02:01 UTC
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

I'm using "range.merge()" to merge cells，but i don't want to show the confirm dialog.
![image](https://github.com/user-attachments/assets/dcc68ce6-2687-42ca-bf94-4e33c76333a9)
Would it be better to use 'range.merge(false)' or 'range.mergeWithNoConfirm()' ?

**Comment by sushiltechnex** [comment] 2024-10-28 15:11
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by hexf00** [comment] 2024-11-25 06:12
Duplicate of #3633

**Closed by hexf00** 2024-11-25 06:12 UTC
Labels: feature request, scope:merged cell
