### ISSUE TITLE
[Feature] rpc error when loading custom function

### ISSUE THREAD

**Issue by luckyguanxin** [dream-num/univer#3151] opened 2024-08-22 04:49 UTC
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

worker.ts；
`import {LocaleType, LogLevel, Tools, Univer} from '@univerjs/core';
import { UniverFormulaEnginePlugin } from '@univerjs/engine-formula';
import { UniverRPCWorkerThreadPlugin } from '@univerjs/rpc';
import { UniverSheetsPlugin } from '@univerjs/sheets';
import { UniverSheetsFilterUIWorkerPlugin } from '@univerjs/sheets-filter-ui';
import {UniverRemoteSheetsFormulaPlugin, UniverSheetsFormulaPlugin} from '@univerjs/sheets-formula';
import { enUS, ruRU, viVN, zhCN, zhTW } from '../locales';
import {FUNCTION_LIST_USER, functionUser} from "./custom-function";

// Univer web worker is also a univer application.
const univer = new Univer({
    locale: LocaleType.ZH_CN,
    logLevel: LogLevel.VERBOSE,
    locales: {
        [LocaleType.ZH_CN]: zhCN,
        [LocaleType.EN_US]: enUS,
        [LocaleType.RU_RU]: ruRU,
        [LocaleType.ZH_TW]: zhTW,
        [LocaleType.VI_VN]: viVN,
    },
});

univer.registerPlugin(UniverSheetsPlugin, { onlyRegisterFormulaRelatedMutations: true });
univer.registerPlugin(UniverFormulaEnginePlugin, { function: functionUser });
univer.registerPlugin(UniverSheetsFormulaPlugin, { description: FUNCTION_LIST_USER });
univer.registerPlugin(UniverRPCWorkerThreadPlugin);
univer.registerPlugin(UniverRemoteSheetsFormulaPlugin);
univer.registerPlugin(UniverSheetsFilterUIWorkerPlugin);

declare let self: WorkerGlobalScope & typeof globalThis & { univer: Univer };
self.univer = univer;`
报错：Uncaught (in promise) [redi]: Cannot find "engine-render.render-manager.service" registered by any injector. The stack of dependencies is: "engine-render.render-manager.service".
报错：Error: [CommandService]: command "formula.mutation.set-formula-calculation-start" is not registered.

### 解决方案

正常运行

**Comment by jikkai** [comment] 2024-08-22 06:08
Please provide the minimal reproduction.

**Comment by luckyguanxin** [comment] 2024-08-22 06:32
> 请提供最低限度的复制品。

你好，rpc怎么加载自定义的公式呢？我上面提到的报错是在worker线程了加载我自己定义的公式报错。 @jikkai

**Comment by jikkai** [comment] 2024-08-22 06:59
请提供最小复现 demo 的链接或者仓库

**Comment by jikkai** [comment] 2024-08-29 06:07
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-08-29 06:07 UTC
Labels: need more info, need reproduction
