### ISSUE TITLE
[Bug] fontFamily does not take effect

### ISSUE THREAD

**Issue by 840251442** [dream-num/univer#3360] opened 2024-09-07 03:20 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.6

### Reproduction link

[fontFamily.zip](https://github.com/user-attachments/files/16914183/fontFamily.zip)
![6271725619845_ pic](https://github.com/user-attachments/assets/bc9fd5a6-14d5-458b-8351-baf3fff72a66)

### Expected behavior

期望跟我截取的excel 字体一样

### Actual behavior

实际这几种字体都没什么区别在univer里面

**Comment by jikkai** [comment] 2024-09-07 03:24
Duplicate of #2177

**Closed by jikkai** 2024-09-07 03:24 UTC
Labels: bug, duplicate
