### ISSUE TITLE
[Feature] Text Formula FIND

### ISSUE THREAD

**Issue by sagarwal3005** [dream-num/univer#2494] opened 2024-06-12 12:53 UTC
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

Text Formula FIND

### Solution

@sagarwal3005: I can solve it

**Comment by Dushusir** [comment] 2024-10-21 07:55
Duplicate of https://github.com/dream-num/univer/issues/1812

**Closed by Dushusir** 2024-10-21 07:55 UTC
Labels: feature request, scope:formula
