### ISSUE TITLE
[Feature] when i migrate luckysheet to univer, how register sheet scroll event by univer 

### ISSUE THREAD

**Issue by xuequanyang** [dream-num/univer#3414] opened 2024-09-12 07:42 UTC
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

when use luckysheet, i register sheet scroll event by hook，but when i migrate luckysheet to univer, i can't find any document how use hook for sheet scroll。can you help me？
these is my code when use luckysheet:
      window.options = {
          container: 'luckysheet', //luckysheet is the container id
          lang: window.sLang, // 设定表格语言
        data:[{
          name: 'zte-sheet',
          index: '1',
          status: 1,
          order: 0,
          hidden: 0,
          celldata: cellData, // 表格数据
          config:{
              columnlen: rowColumnStyle.columnWidthMap,// 列宽设置
              rowlen: rowColumnStyle.rowHeightMap,// 行高设置
              borderInfo: borderInfo, //边框设置
              rowhidden: $.filterHiddenRows(rowColumnStyle.rowHeightMap),// 隐藏行设置
              merge:mergeConfig, //合并单元格
          }
        }],
        row: initRows,//初始化空白行
        column: window.maxColumn,//初始化空白列
        // 回调函数
        hook: {
                
                scroll: function (postion) {
                    var currentScrollTime = new Date().getTime();
                    if(currentScrollTime -lastScrollTime < 1000) {
                       return;
                    }
                    lastScrollTime = currentScrollTime;
                     // 向下滚动时，加载分段数据
                    var currentScrollTop = postion.scrollTop;
                    if(currentScrollTop > scrollTop) {
                        scrollDown = true;
                    }else {
                        scrollDown = false;
                    }
                    scrollTop = currentScrollTop;
                    if (!window.isLoading && scrollDown && window.dataRangeToken) {
                        // 加载更多行记录
                        $.loadMoreRows(sheetIndex);
                    }else {
                        return;
                    }
                },

        }
    }

    luckysheet.create(window.options);

**Comment by jikkai** [comment] 2024-09-12 08:33
Duplicate of #3191

**Closed by jikkai** 2024-09-12 08:33 UTC
Labels: duplicate, feature request
