### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kl-wangxiang** [dream-num/univer#3138] opened 2024-08-21 07:38 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

[redi]: Cannot find "univer-pro.exchange-client.exchange.service" registered by any injector. The stack of dependencies is: "univer-pro.exchange-client.exchange.service".     at DependencyNotFoundError2.RediError [as constructor] (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:6177)     at new DependencyNotFoundError (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:14261)     at onParent (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34362)     at Injector2.createDependency (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34515)     at Injector2._get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:27510)     at Injector2.get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:26915)     at i.importXLSXToSnapshot (webpack-internal:///./node_modules/@univerjs-pro/facade/lib/es/index.js:57:48)     at VueComponent.univer (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:95:17)     at VueComponent.handFile (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:68:12)     at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2924:26)

### Reproduction link

[redi]: Cannot find "univer-pro.exchange-client.exchange.service" registered by any injector. The stack of dependencies is: "univer-pro.exchange-client.exchange.service".
    at DependencyNotFoundError2.RediError [as constructor] (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:6177)
    at new DependencyNotFoundError (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:14261)
    at onParent (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34362)
    at Injector2.createDependency (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34515)
    at Injector2._get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:27510)
    at Injector2.get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:26915)
    at i.importXLSXToSnapshot (webpack-internal:///./node_modules/@univerjs-pro/facade/lib/es/index.js:57:48)
    at VueComponent.univer (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:95:17)
    at VueComponent.handFile (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:68:12)
    at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2924:26)

### Expected behavior

[redi]: Cannot find "univer-pro.exchange-client.exchange.service" registered by any injector. The stack of dependencies is: "univer-pro.exchange-client.exchange.service".
    at DependencyNotFoundError2.RediError [as constructor] (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:6177)
    at new DependencyNotFoundError (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:14261)
    at onParent (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34362)
    at Injector2.createDependency (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34515)
    at Injector2._get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:27510)
    at Injector2.get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:26915)
    at i.importXLSXToSnapshot (webpack-internal:///./node_modules/@univerjs-pro/facade/lib/es/index.js:57:48)
    at VueComponent.univer (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:95:17)
    at VueComponent.handFile (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:68:12)
    at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2924:26)

### Actual behavior

[redi]: Cannot find "univer-pro.exchange-client.exchange.service" registered by any injector. The stack of dependencies is: "univer-pro.exchange-client.exchange.service".
    at DependencyNotFoundError2.RediError [as constructor] (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:6177)
    at new DependencyNotFoundError (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:14261)
    at onParent (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34362)
    at Injector2.createDependency (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34515)
    at Injector2._get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:27510)
    at Injector2.get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:26915)
    at i.importXLSXToSnapshot (webpack-internal:///./node_modules/@univerjs-pro/facade/lib/es/index.js:57:48)
    at VueComponent.univer (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:95:17)
    at VueComponent.handFile (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:68:12)
    at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2924:26)

### System information

[redi]: Cannot find "univer-pro.exchange-client.exchange.service" registered by any injector. The stack of dependencies is: "univer-pro.exchange-client.exchange.service".
    at DependencyNotFoundError2.RediError [as constructor] (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:6177)
    at new DependencyNotFoundError (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:14261)
    at onParent (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34362)
    at Injector2.createDependency (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:34515)
    at Injector2._get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:27510)
    at Injector2.get (webpack-internal:///./node_modules/@univerjs/core/lib/es/index.js:733:26915)
    at i.importXLSXToSnapshot (webpack-internal:///./node_modules/@univerjs-pro/facade/lib/es/index.js:57:48)
    at VueComponent.univer (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:95:17)
    at VueComponent.handFile (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:68:12)
    at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2924:26)

**Comment by jikkai** [comment] 2024-08-21 09:27
Please provide the minimal reproduction.

**Comment by jikkai** [comment] 2024-08-26 06:53
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-08-26 06:53 UTC
Labels: need more info, need reproduction
