### ISSUE TITLE
[Bug] When there is a formula in a row, if you delete a row, the formula will not be deleted.

### ISSUE THREAD

**Issue by semmywong** [dream-num/univer#2312] opened 2024-05-24 06:51 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.1.11

### Reproduction link

https://univer.ai/zh-CN/playground

### Expected behavior

可以正常删除一行

### Actual behavior

删除不成功，删除另外一行的公式，前一行的公式又出现

**Comment by jikkai** [comment] 2024-05-25 06:46
Duplicate of #2311

**Closed by jikkai** 2024-05-25 06:46 UTC
Labels: bug
