### ISSUE TITLE
after import the @univerjs-pro/sheets-pivot and @univerjs-pro/sheets-pivot-ui, I got the error

### ISSUE THREAD

**Issue by hyman928** [dream-num/univer#3023] opened 2024-08-12 07:38 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.7

### Reproduction link

<img width="685" alt="error-pic" src="https://github.com/user-attachments/assets/3e2ddf5e-65a7-44f2-8aa0-98058da1f618">

after import the @univerjs-pro/sheets-pivot and @univerjs-pro/sheets-pivot-ui, I got the error

### Expected behavior

run without error

### Actual behavior

got the error 

### System information

mac、chrome

**Comment by jikkai** [comment] 2024-08-12 07:41
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-08-12 07:41 UTC
Labels: bug

**Comment by hyman928** [comment] 2024-08-12 07:56
before import the plugins and register, program is running normally。But ，after  i import the two plugins, my program reported an error, the picture I uploaded can see the wrong content。I don't know how to solve this problem.

**Comment by jikkai** [comment] 2024-08-12 08:04
Without a minimal reproduction that meets the issue requirements, those who want to help you will face a black box environment, making debugging difficult. To ensure efficient assistance, please provide a minimal reproduction first.

**Comment by hyman928** [comment] 2024-08-12 08:21
【my code:】
import { UniverSheetsPivotTablePlugin } from '@univerjs-pro/sheets-pivot';
import { UniverSheetsPivotTableUIPlugin } from '@univerjs-pro/sheets-pivot-ui';

univer.registerPlugin(UniverSheetsPivotTablePlugin);
univer.registerPlugin(UniverSheetsPivotTableUIPlugin);

**********************************************************************************
【what i tried but fail】

I tried to annotate the code below but still reported the error

univerAPI.executeCommand('sheet.operation.set-selections', {
      selections: [{
        range: {
          startRow: 0,
          startColumn: 0,
          endRow: 0,
          endColumn: 0,
          rangeType: 0,
        },
      }],
      subUnitId,
      unitId: activeWorkbook.getId(),
      type: 2,
    })

************************************************************************************
the error info:

Error: [CommandService]: command "sheet.operation.set-selections" is not registered.
    at _a2.syncExecuteCommand (chunk-SIDV3ZSS.js?v=52dfaa12:8910:13)
    at Object.next (chunk-RRJKU3TX.js?v=52dfaa12:14087:134)
    at ConsumerObserver2.next (chunk-SIDV3ZSS.js?v=52dfaa12:359:25)
    at Subscriber2._next (chunk-SIDV3ZSS.js?v=52dfaa12:329:22)
    at Subscriber2.next (chunk-SIDV3ZSS.js?v=52dfaa12:302:12)
    at BehaviorSubject2._subscribe (chunk-SIDV3ZSS.js?v=52dfaa12:974:40)
    at Observable2._trySubscribe (chunk-SIDV3ZSS.js?v=52dfaa12:500:19)
    at Subject2._trySubscribe (chunk-SIDV3ZSS.js?v=52dfaa12:892:43)
    at chunk-SIDV3ZSS.js?v=52dfaa12:494:115
    at errorContext (chunk-SIDV3ZSS.js?v=52dfaa12:269:5)

chunk-SIDV3ZSS.js?v=52dfaa12:225 Uncaught TypeError: Cannot read properties of undefined (reading 'isServer')
    at $e.onStarting (chunk-UTFT4PEA.js?v=52dfaa12:4033:324)
    at chunk-SIDV3ZSS.js?v=52dfaa12:14468:64
    at Array.forEach (<anonymous>)
    at _a10._runStage (chunk-SIDV3ZSS.js?v=52dfaa12:14461:13)
    at Object.next (chunk-SIDV3ZSS.js?v=52dfaa12:14458:89)
    at ConsumerObserver2.next (chunk-SIDV3ZSS.js?v=52dfaa12:359:25)
    at Subscriber2._next (chunk-SIDV3ZSS.js?v=52dfaa12:329:22)
    at Subscriber2.next (chunk-SIDV3ZSS.js?v=52dfaa12:302:12)
    at Observable2._subscribe (chunk-SIDV3ZSS.js?v=52dfaa12:1771:18)
    at Observable2._trySubscribe (chunk-SIDV3ZSS.js?v=52dfaa12:500:19)

**Comment by jikkai** [comment] 2024-08-12 08:39
```diff
- univer.registerPlugin(UniverSheetsPivotTablePlugin);
+ univer.registerPlugin(UniverSheetsPivotTablePlugin, { isServer: false });
```

**Comment by hyman928** [comment] 2024-08-12 08:46
The last problem was solved, but new problems occurred：
chunk-VXB7U7RG.js?v=8b408611:7721 Uncaught Error: [redi]: Expect "required" dependency items for id "ye" but get 2.
    at QuantityCheckError2.RediError [as constructor] (chunk-VXB7U7RG.js?v=8b408611:7721:21)
    at new QuantityCheckError (chunk-VXB7U7RG.js?v=8b408611:7834:21)
    at checkQuantity (chunk-VXB7U7RG.js?v=8b408611:7841:11)
    at DependencyCollection2.get (chunk-VXB7U7RG.js?v=8b408611:7965:14)
    at onSelf (chunk-VXB7U7RG.js?v=8b408611:8423:56)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:119)
    at Injector2._get (chunk-VXB7U7RG.js?v=8b408611:8290:19)
    at Injector2.get (chunk-VXB7U7RG.js?v=8b408611:8277:28)
    at chunk-VXB7U7RG.js?v=8b408611:13774:76
    at Array.forEach (<anonymous>)

chunk-VXB7U7RG.js?v=8b408611:7721 Uncaught Error: [redi]: Cannot find "Fe" registered by any injector. The stack of dependencies is: "fe -> Fe".
    at DependencyNotFoundError2.RediError [as constructor] (chunk-VXB7U7RG.js?v=8b408611:7721:21)
    at new DependencyNotFoundError (chunk-VXB7U7RG.js?v=8b408611:7942:29)
    at onParent (chunk-VXB7U7RG.js?v=8b408611:8432:39)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:130)
    at Injector2._get (chunk-VXB7U7RG.js?v=8b408611:8290:19)
    at Injector2._resolveClassImpl (chunk-VXB7U7RG.js?v=8b408611:8356:30)
    at Injector2._resolveClass (chunk-VXB7U7RG.js?v=8b408611:8342:22)
    at Injector2._resolveDependency (chunk-VXB7U7RG.js?v=8b408611:8309:220)
    at onSelf (chunk-VXB7U7RG.js?v=8b408611:8426:44)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:119)

chunk-VXB7U7RG.js?v=8b408611:7721 Uncaught (in promise) Error: [redi]: Cannot find "Re" registered by any injector. The stack of dependencies is: "mr -> Re".
    at DependencyNotFoundError2.RediError [as constructor] (chunk-VXB7U7RG.js?v=8b408611:7721:21)
    at new DependencyNotFoundError (chunk-VXB7U7RG.js?v=8b408611:7942:29)
    at onParent (chunk-VXB7U7RG.js?v=8b408611:8432:39)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:130)
    at onParent (chunk-VXB7U7RG.js?v=8b408611:8429:31)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:130)
    at Injector2._get (chunk-VXB7U7RG.js?v=8b408611:8290:19)
    at Injector2._resolveClassImpl (chunk-VXB7U7RG.js?v=8b408611:8356:30)
    at Injector2.createInstance (chunk-VXB7U7RG.js?v=8b408611:8301:72)
    at useFactory (chunk-UKX2EJGS.js?v=8b408611:32892:57)

chunk-VXB7U7RG.js?v=8b408611:7721 Uncaught Error: [redi]: Expect "required" dependency items for id "ye" but get 2.
    at QuantityCheckError2.RediError [as constructor] (chunk-VXB7U7RG.js?v=8b408611:7721:21)
    at QuantityCheckError2.QuantityCheckError [as constructor] (chunk-VXB7U7RG.js?v=8b408611:7834:21)
    at checkQuantity (chunk-VXB7U7RG.js?v=8b408611:7841:11)
    at DependencyCollection2.get (chunk-VXB7U7RG.js?v=8b408611:7965:14)
    at onSelf (chunk-VXB7U7RG.js?v=8b408611:8423:56)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:119)
    at Injector2._get (chunk-VXB7U7RG.js?v=8b408611:8290:19)
    at Injector2.get (chunk-VXB7U7RG.js?v=8b408611:8277:28)
    at chunk-VXB7U7RG.js?v=8b408611:13774:76
    at Array.forEach (<anonymous>)

chunk-VXB7U7RG.js?v=8b408611:7721 Uncaught Error: [redi]: Cannot find "Fe" registered by any injector. The stack of dependencies is: "fe -> Fe".
    at DependencyNotFoundError2.RediError [as constructor] (chunk-VXB7U7RG.js?v=8b408611:7721:21)
    at new DependencyNotFoundError (chunk-VXB7U7RG.js?v=8b408611:7942:29)
    at onParent (chunk-VXB7U7RG.js?v=8b408611:8432:39)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:130)
    at Injector2._get (chunk-VXB7U7RG.js?v=8b408611:8290:19)
    at Injector2._resolveClassImpl (chunk-VXB7U7RG.js?v=8b408611:8356:30)
    at Injector2._resolveClass (chunk-VXB7U7RG.js?v=8b408611:8342:22)
    at Injector2._resolveDependency (chunk-VXB7U7RG.js?v=8b408611:8309:220)
    at onSelf (chunk-VXB7U7RG.js?v=8b408611:8426:44)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:119)

chunk-VXB7U7RG.js?v=8b408611:7721 Uncaught Error: [redi]: Cannot find "Re" registered by any injector. The stack of dependencies is: "hr -> Re".
    at DependencyNotFoundError2.RediError [as constructor] (chunk-VXB7U7RG.js?v=8b408611:7721:21)
    at new DependencyNotFoundError (chunk-VXB7U7RG.js?v=8b408611:7942:29)
    at onParent (chunk-VXB7U7RG.js?v=8b408611:8432:39)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:130)
    at Injector2._get (chunk-VXB7U7RG.js?v=8b408611:8290:19)
    at Injector2._resolveClassImpl (chunk-VXB7U7RG.js?v=8b408611:8356:30)
    at Injector2._resolveClass (chunk-VXB7U7RG.js?v=8b408611:8342:22)
    at Injector2._resolveDependency (chunk-VXB7U7RG.js?v=8b408611:8309:220)
    at onSelf (chunk-VXB7U7RG.js?v=8b408611:8426:44)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:119)

chunk-VXB7U7RG.js?v=8b408611:225 Uncaught TypeError: Cannot read properties of undefined (reading 'with')
    at _a40._commandExecutedListener (chunk-5AIP4QZ7.js?v=8b408611:18832:103)
    at _a40._initialize (chunk-5AIP4QZ7.js?v=8b408611:18829:10)
    at new FormatPainterController (chunk-5AIP4QZ7.js?v=8b408611:18826:361)
    at Injector2._resolveClassImpl (chunk-VXB7U7RG.js?v=8b408611:8368:19)
    at Injector2._resolveClass (chunk-VXB7U7RG.js?v=8b408611:8342:22)
    at Injector2._resolveDependency (chunk-VXB7U7RG.js?v=8b408611:8309:220)
    at onSelf (chunk-VXB7U7RG.js?v=8b408611:8426:44)
    at Injector2.createDependency (chunk-VXB7U7RG.js?v=8b408611:8434:119)
    at Injector2._get (chunk-VXB7U7RG.js?v=8b408611:8290:19)
    at Injector2.get (chunk-VXB7U7RG.js?v=8b408611:8277:28)

**Comment by jikkai** [comment] 2024-08-12 08:48
Let me reiterate, please provide the minimal reproduction.

**Comment by hyman928** [comment] 2024-08-12 08:53
code：


  import { UniverSheetsPivotTablePlugin } from '@univerjs-pro/sheets-pivot';
  import { UniverSheetsPivotTableUIPlugin } from '@univerjs-pro/sheets-pivot-ui';

   univer.registerPlugin(UniverSheetsPivotTablePlugin, { isServer: true })
   univer.registerPlugin(UniverSheetsPivotTableUIPlugin);

**Comment by hyman928** [comment] 2024-08-13 01:02
请问这个问题该如何解决呢？

**Comment by jikkai** [comment] 2024-08-13 02:28
reproduction link plz.

**Comment by hyman928** [comment] 2024-08-13 02:38
link about my issues？

https://github.com/dream-num/univer/issues/3023
