### ISSUE TITLE
[Bug] Cannot find "ui.shortcut.service" registered by any injector. in 0.4.1

### ISSUE THREAD

**Issue by wssnail** [dream-num/univer#3834] opened 2024-10-23 10:35 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.1

### Reproduction link

none

### Expected behavior

Expect to function correctly in 0.4.1

### Actual behavior

Code that works fine in version 0.2.15, but the following error occurs in version 0.4.1
`Cannot find "ui.shortcut.service" registered by any injector. The stack of dependencies is: "ui.shortcut.service".`

### System information

vue3.5.5
vite4.5.5
univer 0.4.1

**Comment by jikkai** [comment] 2024-10-23 12:07
Since you have not provided the minimum reproduction and sufficient information as required by community guidelines, we will close this issue for now. When you are ready with a demo link or repository that can reproduce the problem, feel free to reopen it at any time.

**Closed as completed by jikkai** 2024-10-23 12:07 UTC
Labels: need reproduction

**Comment by shijieo0** [comment] 2025-01-21 04:36
"Expect \"required\" dependency items for id \"ui.shortcut.service\" but get 0. Did you forget to register it?"
