### ISSUE TITLE
[Bug] native error in mobile browser

### ISSUE THREAD

**Issue by yooyea** [dream-num/univer#2181] opened 2024-05-08 04:19 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.1.9

### Reproduction link

https://github.com/yooyea/univer-mobile/tree/master

### Expected behavior

Not error

### Actual behavior

Throw error

### System information

Iphone12 ios 16.3

**Comment by yooyea** [comment] 2024-05-08 04:19
![b3b3b5dc-6612-4f6c-a3bf-fcbcb51e6a5c](https://github.com/dream-num/univer/assets/66212485/f173c50e-8746-44e9-9857-6948d7d44e27)
![4cf1f35b-4930-4ee2-9065-612049c30194](https://github.com/dream-num/univer/assets/66212485/ac54eb29-1530-4ffd-a5ac-4a477b79deab)

**Comment by jikkai** [comment] 2024-05-08 04:51
Thank you for raising this issue. Unfortunately, we were unable to reproduce the problem in your repository. For now, we will close this issue. If you can provide a new way to reproduce the issue, please feel free to reopen it at any time.

<img width="1993" alt="image" src="https://github.com/dream-num/univer/assets/14025786/9b844657-658c-4809-8a1b-4e974ff7d184">

**Closed by jikkai** 2024-05-08 04:51 UTC
Labels: bug

**Comment by yooyea** [comment] 2024-05-08 06:16
Thank you, it's fine when i deleted node_modules and install depends agian
