### ISSUE TITLE
[Bug] The vue3 template id is placed in the teleport tag and cannot be rendered.

### ISSUE THREAD

**Issue by sunchens** [dream-num/univer#3828] opened 2024-10-23 00:52 UTC
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.1

### 复现链接

 <teleport :to='teleportTo'>
    <div v-show="!previewStatus" ref="container" id="univer-container" class="univer-container"></div>
  </teleport>
const teleportTo = ref('body')
const previewStatus = ref(false)
univer.registerPlugin(UniverUIPlugin, {
  container: 'univer-container',
  footer:false
});

### 预期行为

0.2.12正确渲染出来

### 实际行为

正确渲染

### 运行环境

Chrome

**Comment by jikkai** [comment] 2024-10-23 03:20
Since you have not provided the minimum reproduction and sufficient information as required by community guidelines, we will close this issue for now. When you are ready with a demo link or repository that can reproduce the problem, feel free to reopen it at any time.

**Closed by jikkai** 2024-10-23 03:20 UTC
Labels: bug
