### ISSUE TITLE
[Feature] Improved Cell Focus and Save Behavior in Excel

### ISSUE THREAD

**Issue by yooyea** [dream-num/univer#2190] opened 2024-05-08 08:28 UTC
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

**Description:**

Currently, when a user edits a cell in Excel and then clicks the save button outside of the Excel window (rather than using the save option within Excel), the cell does not correctly lose focus. This results in the loss of any unsaved data entered into that cell.

**Reproduction Steps:**

Open Excel and create a new workbook.
Select a cell and enter some data.
Without pressing Enter to confirm the entry, click outside of the Excel window to lose focus on Excel.
Click the save button provided by the operating system.

**Expected Behavior:**

When a user clicks outside the Excel window to lose focus, Excel should automatically save the content of the currently edited cell and lose focus properly.

This issue significantly impacts data integrity and user productivity. It is recommended to treat this as a high-priority feature request.

![image](https://github.com/dream-num/univer/assets/66212485/b7699917-551e-4597-839f-22997314ad13)

### Solution

One possible solution is to modify Excel's behavior to automatically save the content of an edited cell upon losing focus.

**Comment by jikkai** [comment] 2024-05-08 11:03
Duplicate of #1314

**Closed by jikkai** 2024-05-08 11:03 UTC
Labels: feature request
