### ISSUE TITLE
[Bug] dropdown arrow still appears when set contextMenu: false

### ISSUE THREAD

**Issue by linen1794** [dream-num/univer#3442] opened 2024-09-14 03:08 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.9

### Reproduction link

Thank you for your open-source contribution; it has been incredibly helpful to me. However, I’ve encountered a small issue. When I set contextMenu: false, a dropdown button still appears when I hover over the column header. I’m not sure whether this is a bug or if I’m missing some configuration. I would really appreciate your help. Thank you![https://codesandbox.io/p/devbox/cool-morning-7r8tkd?file=%2Findex.js%3A52%2C29](url)
![Uploading WX20240914-110648@2x.png…]()

### Expected behavior

dropdown arrow disappear

### Actual behavior

dropdown arrow appear

**Comment by jikkai** [comment] 2024-09-14 03:51
Duplicate of #3145

**Closed by jikkai** 2024-09-14 03:51 UTC
Labels: bug, duplicate
