### ISSUE TITLE
[Bug] why always show ”more“ ？

### ISSUE THREAD

**Issue by elevenwangyang** [dream-num/univer#4356] opened 2024-12-24 07:03 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.5.1

### Reproduction link

![image](https://github.com/user-attachments/assets/165991d5-fe75-4a5b-a123-449c783f6671)

### Expected behavior

Show all according to the space

### Actual behavior

always show ”more“

**Comment by jikkai** [comment] 2024-12-24 07:16
Duplicate of #4053

**Closed by jikkai** 2024-12-24 07:16 UTC
Labels: bug, duplicate
