### ISSUE TITLE
[Bug] Moving with keyboard arrows remove the focus from editing cells.

### ISSUE THREAD

**Issue by joanengenhoff** [dream-num/univer#1925] opened 2024-04-16 03:25 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

Sheets

### Reproduction link

https://stackblitz.com/~/github.com/joanengenhoff/sheets-vite-demo

### Expected behavior

When double clicking and the cursor starts to blink, moving with keyboards arrows should move the cursor inside the editing cell.

### Actual behavior

When double clicking and the cursor starts to blink, moving with keyboards arrows also moves the focus to other cells.

![Carnac_U8vj6Lq8nV](https://github.com/dream-num/univer/assets/166045912/9e984e27-1b09-430c-944f-0d3565a52624)

### System information

System:
OS: macOS 14.2.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 16.38 MB / 32.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
pnpm: 8.15.7 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
Browsers:
Chrome: 123.0.6312.124
Safari: 17.2.1

**Comment by jikkai** [comment] 2024-04-16 04:01
Duplicate of #1549

**Closed by jikkai** 2024-04-16 04:01 UTC
Labels: bug
