### ISSUE TITLE
[Bug] After importing an xlsx file with a drop-down selection, the original drop-down selection of the xlsx is erased when exporting it;

### ISSUE THREAD

**Issue by qiushilong** [dream-num/univer#2884] opened 2024-07-30 02:59 UTC
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

lastest

### 复现链接

https://univer.ai/pro/examples/sheets-exchange

### 预期行为

After importing an xlsx file with a drop-down selection, the original drop-down selection of the xlsx file will not disappear when exporting it again; including other original xlsx formats, the format of the original file should not be changed when importing and exporting;
(导入带下拉选择的xlsx文件后，再导出时xlsx本来的下拉选择不消失；包括其他原来的xlsx格式，在导入再导出时，不应该改变原来文件的格式；)

### 实际行为

After importing an xlsx file with a drop-down selection, the original drop-down selection of the xlsx is erased when exporting it;
(导入带下拉选择的xlsx文件后，再导出时xlsx本来的下拉选择被抹除了;)

### 运行环境

Chrome

**Comment by jikkai** [comment] 2024-07-30 08:14
Please provide the xlsx you used when uploading.

**Comment by jikkai** [comment] 2024-08-06 06:52
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-08-06 06:52 UTC
Labels: bug, need reproduction

**Comment by YanDonkeyBaby** [comment] 2024-08-09 08:39
I also encountered the same problem.
