### ISSUE TITLE
[Bug] custom export menu button click export button api error

### ISSUE THREAD

**Issue by chenyuan4x7** [dream-num/univer#3024] opened 2024-08-12 07:56 UTC
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

^0.2.6

### 复现链接

[https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo](url)

### 预期行为

使用自定义菜单按钮 监听 command.id (use.sheet.command.export.file) 执行 univerAPI.exportXLSXBySnapshot() 方法 返回 fileData  然后通过 downloadFile(fileData, "test", "xlsx") 导入 excel 文件

### 实际行为

exportXLSXBySnapshot 返回 file 为 undefined 

### 运行环境

Chrome

### 系统信息

/universer-api/exchange/task/1821854305443938387 接口 响应  一直处于 pending 状态.
{error: {code: 1, message: "success"}, taskID: "1821854305443938387", status: "pending",…}
error: {code: 1, message: "success"}
export: {fileID: "", fileUrl: ""}
status: "pending"
taskID: "1821854305443938387"

**Comment by chenyuan4x7** [comment] 2024-08-12 07:57
https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

**Comment by jikkai** [comment] 2024-08-12 08:06
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Comment by chenyuan4x7** [comment] 2024-08-12 09:05
> We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.


https://github.com/user-attachments/assets/491e2dc6-cab8-41e5-a141-0eb74bd9baa0

麻烦你看一下我上传的视频效果 看可以复现这个问题吗 谢谢

**Comment by jikkai** [comment] 2024-08-12 09:15
Please provide at least an xlsx sample for us to reproduce the issue.

**Comment by chenyuan4x7** [comment] 2024-08-12 09:16
> Please provide at least an xlsx sample for us to reproduce the issue.

[QQT-LAB-TR-02-702D-00  方法验证报告 OK.xlsx](https://github.com/user-attachments/files/16579656/QQT-LAB-TR-02-702D-00.OK.xlsx)

**Comment by Dushusir** [comment] 2024-11-29 12:50
This issue has been fixed. Please retest with the latest version.
This issue will be closed. If you still have problems, please feel free to reopen it.

**Closed by Dushusir** 2024-11-29 12:50 UTC
Labels: bug, scope:import export
