### ISSUE TITLE
[Bug] Print preview and actual printing issues

### ISSUE THREAD

**Issue by iuouiyiuty** [dream-num/univer#3560] opened 2024-09-24 12:21 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.15

### Reproduction link

同样一段代码，在升级到v0.2.15后工作不正常了

`const activeSheet = univerAPI.getActiveWorkbook().getActiveSheet();
  if(id === "sheet.operation.print-open") {
    const range = activeSheet.getRange(0,excelCellToRowCol('AU'+1).col);
    activeSheet.hideColumn(range);
  }
  if(id === "sheet.operation.cancel-print" || id === "sheet.operation.confirm-print") {
    const range = activeSheet.getRange(0,excelCellToRowCol('AU'+1).col);
    activeSheet.unhideColumn(range);
  }`

工作表
![image](https://github.com/user-attachments/assets/773f49f3-8e94-48a2-bc8b-073f45e58948)

打印预览时
![image](https://github.com/user-attachments/assets/f00db53d-cf8b-467f-a1fc-177dc3ea2723)

打印时
![image](https://github.com/user-attachments/assets/5a3877a9-ce31-4dbf-ae35-d734d81dc35e)

### Expected behavior

打印预览时
- 隐藏AU列
- 底部内容正常展示

打印时
- AU列依旧隐藏
- 底部内容正常展示

### Actual behavior

打印预览时
- 隐藏AU列
- 底部内容展示不正常

打印时
- AU列展示
- 底部内容正常展示

**Comment by iuouiyiuty** [comment] 2024-09-24 15:06
刚才回退到了v0.2.14版本重新试了一下，发现打印预览是好的，但是打印的时候隐藏列的实际表现变成和上面说的一样了。也许我记错了？但v.0.2.14版本我应该是调试好了之后才发布的。

**Comment by weird94** [comment] 2024-09-25 07:53
你这只贴一段代码我跑不起来，为了节省双方的时间，麻烦提供一个 stackblitz 的链接，谢谢。

**Comment by jikkai** [comment] 2024-10-11 03:08
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-10-11 03:08 UTC
Labels: bug, scope:print, need reproduction
