### ISSUE TITLE
[Bug] Copy the merged cells from the table using activeWorkbook?. save() error when saved data is reloaded

### ISSUE THREAD

**Issue by wssnail** [dream-num/univer#3835] opened 2024-10-23 11:09 UTC
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15、0.4.1

### 复现链接

none

### 预期行为

Using activeWorkbook?. save() saved data, can be loaded normally

### 实际行为

The following errors actually occur in 0.2.15 or 0.4.1:
`Cannot destructure property 'width' of 'lastPage' as it is undefined.`

### 运行环境

Chrome

### 系统信息

macos
univer: 0.4.1
vue: 3.5.5
vite: 4.5.5

**Comment by jikkai** [comment] 2024-10-23 12:07
Since you have not provided the minimum reproduction and sufficient information as required by community guidelines, we will close this issue for now. When you are ready with a demo link or repository that can reproduce the problem, feel free to reopen it at any time.

**Closed by jikkai** 2024-10-23 12:07 UTC
Labels: need reproduction

**Comment by wssnail** [comment] 2024-10-24 00:41
![image](https://github.com/user-attachments/assets/04bf91e1-635d-4472-b44d-9644d1964e01)
getDocsSkeletonPageSize does not determine the length of pages

**Comment by wssnail** [comment] 2024-10-24 00:49
> jikkai

This is an operation exception, the code can not be reproduced, you can try according to this operation:

Copy the merged cells from one local excel to univer table，and then using activeWorkbook?. save() the data， error when data is reloaded

**Comment by wssnail** [comment] 2024-10-24 02:12
> Since you have not provided the minimum reproduction and sufficient information as required by community guidelines, we will close this issue for now. When you are ready with a demo link or repository that can reproduce the problem, feel free to reopen it at any time.

I found the wrong reason, may be encountered can not handle the style, the data is as follows:
In line 1, column 0, there's style "p" here, and I delete "p" and I can render it.
```
{"cellData":{
"1": {
          "0": {
            "p": {
              "body": {
                "paragraphs": [
                  {
                    "paragraphStyle": {
                      "horizontalAlign": 2
                    },
                    "startIndex": 21
                  }
                ],
                "dataStream": "（   2024  年度  1   季度）",
                "textRuns": [
                  {
                    "st": 1,
                    "ed": 4,
                    "ts": {
                      "ff": "宋体",
                      "cl": {
                        "rgb": "rgb(0,0,0)"
                      },
                      "fs": 16,
                      "ul": {
                        "s": 1
                      }
                    }
                  },
                  {
                    "st": 4,
                    "ed": 8,
                    "ts": {
                      "ff": "宋体",
                      "cl": {
                        "rgb": "rgb(0,0,0)"
                      },
                      "fs": 16,
                      "ul": {
                        "s": 1
                      }
                    }
                  },
                  {
                    "st": 8,
                    "ed": 10,
                    "ts": {
                      "ff": "宋体",
                      "cl": {
                        "rgb": "rgb(0,0,0)"
                      },
                      "fs": 16,
                      "ul": {
                        "s": 1
                      }
                    }
                  },
                  {
                    "st": 10,
                    "ed": 12,
                    "ts": {
                      "ff": "宋体",
                      "cl": {
                        "rgb": "rgb(0,0,0)"
                      },
                      "fs": 16
                    }
                  },
                  {
                    "st": 12,
                    "ed": 14,
                    "ts": {
                      "ff": "宋体",
                      "cl": {
                        "rgb": "rgb(0,0,0)"
                      },
                      "fs": 16,
                      "ul": {
                        "s": 1
                      }
                    }
                  },
                  {
                    "st": 14,
                    "ed": 15,
                    "ts": {
                      "ff": "宋体",
                      "cl": {
                        "rgb": "rgb(0,0,0)"
                      },
                      "fs": 16,
                      "ul": {
                        "s": 1
                      }
                    }
                  },
                  {
                    "st": 15,
                    "ed": 18,
                    "ts": {
                      "ff": "宋体",
                      "cl": {
                        "rgb": "rgb(0,0,0)"
                      },
                      "fs": 16,
                      "ul": {
                        "s": 1
                      }
                    }
                  },
                  {
                    "st": 18,
                    "ed": 21,
                    "ts": {
                      "ff": "宋体",
                      "cl": {
                        "rgb": "rgb(0,0,0)"
                      },
                      "fs": 16
                    }
                  }
                ]
              },
              "documentStyle": {
                "pageSize": {
                  "width": 247.97760009765625
                },
                "marginLeft": 2,
                "marginRight": 2,
                "renderConfig": {
                  "verticalAlign": 2,
                  "wrapStrategy": 1,
                  "vertexAngle": 0,
                  "horizontalAlign": 2,
                  "centerAngle": 0
                },
                "marginBottom": 2,
                "marginTop": 0
              },
              "drawingsOrder": [

              ],
              "drawings": {

              },
              "id": "d"
            },
            "s": "ZceBLG",
            "t": 1,
            "v": "（   2024  年度  1   季度）"
          },
          "1": {
            "s": "ZceBLG"
          },
          "2": {
            "s": "ZceBLG"
          },
          "3": {
            "s": "ZceBLG"
          },
          "4": {
            "s": "ZceBLG"
          },
          "5": {
            "s": "ZceBLG"
          },
          "6": {
            "s": "ZceBLG"
          },
          "7": {
            "s": "ZceBLG"
          },
          "8": {
            "s": "ZceBLG"
          }
        }
}
}
```
