### ISSUE TITLE
[Bug] Calling DocumentDataModel.apply(actions: JSONXActions) does not rerender visually

### ISSUE THREAD

**Issue by LeosPrograms** [dream-num/univer#3515] opened 2024-09-20 18:32 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.14

### Reproduction link

1. Generate a document using `document1 = univer.createUnit(UniverInstanceType.UNIVER_DOC, {});`
2. Create a JSONXActions object `let jxa = [
    "body",
    {
        "et": "text-x",
        "e": [
            {
                "body": {
                    "dataStream": "a"
                },
                "len": 1,
                "line": 0,
                "segmentId": "",
                "t": "i"
            }
        ]
    }
]`
3. Apply the JSONXActions with `document1.apply(jxa)`

### Expected behavior

Changes are applied, and the document updates visually.

### Actual behavior

Changes are applied to the Univer doc object, but they are not reflected visually. Changes are updated visually only after manual adjustments, or after a command is executed.

### System information

Running in electron on Ubuntu 22.04.4

**Comment by Jocs** [comment] 2024-09-21 07:15
Any error message in console?

**Comment by LeosPrograms** [comment] 2024-09-21 10:34
No, none.

**Comment by Jocs** [comment] 2024-10-10 09:48
@LeosPrograms Can you provide a minimal demo for reproduce this issue?

**Comment by jikkai** [comment] 2024-10-21 07:47
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Closed by jikkai** 2024-10-21 07:47 UTC
Labels: bug, need more info
