### ISSUE TITLE
[Bug] formula =I4/$I$23 =SUMIF($C:$C,V3,$I:$I) don't work!

### ISSUE THREAD

**Issue by Picktarget** [dream-num/univer#2778] opened 2024-07-16 07:34 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.2

### Reproduction link

https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo

### Expected behavior

formula =I4/$I$23 =SUMIF($C:$C,V3,$I:$I)  work

### Actual behavior

The formula doesn't work

**Comment by jikkai** [comment] 2024-07-16 08:32
We are closing this issue for now due to the lack of enough information. Please feel free to reopen it once you can provide a minimal reproduction.

**Comment by Picktarget** [comment] 2024-07-16 14:53
https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts here is my reproduction

**Comment by Picktarget** [comment] 2024-07-16 14:53
@jikkai there is no re-open button for me

**Comment by jikkai** [comment] 2024-07-17 02:54
> https://stackblitz.com/~/github.com/awesome-univer/sheets-vite-demo?file=src/main.ts here is my reproduction

It's just an official demo, not your repro.

**Comment by Picktarget** [comment] 2024-07-18 03:58
@jikkai https://stackblitz.com/~/github.com/Picktarget/vitejs-vite-1ztedz?file=src/App.vue how about this? I just make a new repo to reproduce it

**Comment by jikkai** [comment] 2024-07-19 02:50
> @jikkai https://stackblitz.com/~/github.com/Picktarget/vitejs-vite-1ztedz?file=src/App.vue how about this? I just make a new repo to reproduce it

This is still an invalid repro.

**Comment by Picktarget** [comment] 2024-07-19 05:45
@jikkai please try it again https://stackblitz.com/~/github.com/Picktarget/vitejs-vite-1ztedz?file=src/App.vue I just commit my changes failed due to the network T.T

**Comment by jikkai** [comment] 2024-07-19 06:38
@Dushusir Should have a look.

**Comment by Dushusir** [comment] 2024-07-19 07:02
We will process it as soon as possible

**Comment by Picktarget** [comment] 2024-07-29 08:41
@Dushusir hello Is there any progress?

**Comment by Dushusir** [comment] 2024-08-14 07:06
fixed

**Comment by Picktarget** [comment] 2024-08-14 07:20
@Dushusir maybe u should test with the link https://stackblitz.com/~/github.com/Picktarget/vitejs-vite-1ztedz?file=src/App.vue . It happens if I render formula from workbook data

**Closed** 2024-08-23 01:38 UTC
Labels: scope:formula
