### ISSUE TITLE
[Feature] How to switch to preview mode in edit mode?

### ISSUE THREAD

**Issue by smallCF** [dream-num/univer#4154] opened 2024-11-26 06:29 UTC
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

我现在编辑页面编写后保存，发送给比人看，但是不想然别人修改，如何设置只能预览模式？

**Comment by smallCF** [comment] 2024-11-26 08:58
I looked through previous issues and found a function method called setEditable that sets editing disabled. I followed the example of this issue and wrote it down
Unable to obtain setEditable, I am using @ univer/ core@0.5.0 The version

**Comment by jikkai** [comment] 2024-11-27 07:25
Please provide the minimal reproduction.

**Comment by jikkai** [comment] 2024-12-03 06:16
Since you have not provided a reproduction according to the community guidelines, we will close this issue. Once you have prepared a reproduction, feel free to reopen it at any time.

**Closed by jikkai** 2024-12-03 06:16 UTC
Labels: need reproduction
