### ISSUE TITLE
[Bug] Error deleting selected row

### ISSUE THREAD

**Issue by huahunanhuahu** [dream-num/univer#4151] opened 2024-11-26 01:59 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

用最新0.5.0版本测试问题仍然存在

### Reproduction link

1.创建sheet2
![image](https://github.com/user-attachments/assets/1dc9f369-66ed-4dd3-aef8-b5fc8a8cd76e)

2.在sheet3中引用sheet2的数据，其中最后一行是每行的总计(使用公式SUM)，最后一列是每列的总计(使用公式SUM)
![image](https://github.com/user-attachments/assets/01a5c436-8544-4984-bc97-32dd64368e0e)

3.删除某选中行

### Expected behavior

该选中行被删除

### Actual behavior

该选中行未被删除，删除的是除总计行外的最后一行
![image](https://github.com/user-attachments/assets/0952dd38-a237-4e09-ac21-07675c339a7a)

**Comment by Dushusir** [comment] 2024-11-28 08:37
Can you provide a complete sample?

**Comment by jikkai** [comment] 2024-12-03 06:17
Since you have not provided a reproduction according to the community guidelines, we will close this issue. Once you have prepared a reproduction, feel free to reopen it at any time.

**Closed by jikkai** 2024-12-03 06:17 UTC
Labels: scope:formula, need reproduction
