### ISSUE TITLE
[Bug] Disable floating images in images, the image label does not become unselectable or disappear

### ISSUE THREAD

**Issue by BugExpert** [dream-num/univer#3793] opened 2024-10-18 08:41 UTC
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.4.0

### 复现链接

图片标签没有变灰

### 预期行为

![image](https://github.com/user-attachments/assets/9e64a323-b976-460b-838f-e908a3114675)

### 实际行为

![image](https://github.com/user-attachments/assets/d20bedfb-8326-4735-8053-93540b29472c)

**Comment by jikkai** [comment] 2024-10-18 08:53
Please provide the minimal reproduction.

**Comment by jikkai** [comment] 2024-10-23 12:08
Since you have not provided the minimum reproduction and sufficient information as required by community guidelines, we will close this issue for now. When you are ready with a demo link or repository that can reproduce the problem, feel free to reopen it at any time.

**Closed by jikkai** 2024-10-23 12:08 UTC
Labels: need reproduction
