### ISSUE TITLE
Horizontal scroll axis appears even though the columns of the table are not filled up

### ISSUE THREAD

**Issue by maotong06** [dream-num/univer#2968] opened 2024-08-08 01:45 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.6

### Reproduction link

https://univer.ai/zh-CN/examples/sheets
in the hyperlink sheet
![image](https://github.com/user-attachments/assets/4b9f48a9-c5a6-4b8c-9ce2-6987032f6f10)

### Expected behavior

Hopefully no scroll axis when the front column just fills up the space

### Actual behavior

Hopefully no scroll axis when the front column just fills up the space

**Comment by jikkai** [comment] 2024-08-08 03:47
Duplicate of #2836

**Closed by jikkai** 2024-08-08 03:47 UTC
Labels: bug
