### ISSUE TITLE
[Bug] Exit Cell editing cannot get the coordinates of the current exit cell

### ISSUE THREAD

**Issue by 335060087** [dream-num/univer#4232] opened 2024-12-05 02:15 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.2

### Reproduction link

Exit Cell editing cannot get the coordinates of the current exit cell

### Expected behavior

Listen to exit cell edit to get cell coordinates

### Actual behavior

Now listen to exit cell edit without cell coordinates

### System information

chrom

**Comment by jikkai** [comment] 2024-12-05 03:09
Since you have not provided a reproduction according to the community guidelines, we will close this issue. Once you have prepared a reproduction, feel free to reopen it at any time.

**Closed** 2024-12-05 03:09 UTC
Labels: need reproduction
