### ISSUE TITLE
[Bug] Missing `paragraphs` or `sectionBreaks` fields, or doesn't correspond to the location in `dataStream` while insert '+' chractor

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#2731] opened 2024-07-09 10:08 UTC
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.2.0

### Reproduction link

add `+` in any column: 
https://sheetsvitedemo-s2r2--5173--70dbe416.local-credentialless.webcontainer.io

### Expected behavior

maybe can accept like `+` special chracter, or has any feedback in UI

### Actual behavior

Missing `paragraphs` or `sectionBreaks` fields, or doesn't correspond to the location in `dataStream`

**Comment by jikkai** [comment] 2024-07-09 12:23
Duplicate of #2725

**Closed by jikkai** 2024-07-09 12:23 UTC
Labels: bug
